"""add state_date to notes

Revision ID: 061826754c60
Revises: 9006ee86d4fe
Create Date: 2025-04-17 11:13:26.057710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061826754c60'
down_revision: Union[str, None] = '9006ee86d4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('status_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'status_date')
    # ### end Alembic commands ###
