"""Unique user email constraint

Revision ID: cb3782557c1e
Revises: e4b7fc94d40b
Create Date: 2025-04-01 09:25:09.604715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3782557c1e'
down_revision: Union[str, None] = 'e4b7fc94d40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_email", 'user_account', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_email", 'user_account', type_='unique')
    # ### end Alembic commands ###
